artifact_uri: file:///home/mle-user/mle_projects/mlflow/mlflow_experiments_store/0/ce7f6a339b894b2ea99248cd3df47fff/artifacts
end_time: 1766721308332
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ce7f6a339b894b2ea99248cd3df47fff
run_name: Default
run_uuid: ce7f6a339b894b2ea99248cd3df47fff
source_name: ''
source_type: 4
source_version: ''
start_time: 1766721308322
status: 4
tags: []
user_id: mle-user
