artifact_uri: file:///home/mle-user/mle_projects/mlflow/mlflow_experiments_store/0/6b2210e71f864a5dbc8b4eaa9f15fce8/artifacts
end_time: 1766721587644
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6b2210e71f864a5dbc8b4eaa9f15fce8
run_name: Default
run_uuid: 6b2210e71f864a5dbc8b4eaa9f15fce8
source_name: ''
source_type: 4
source_version: ''
start_time: 1766721587632
status: 4
tags: []
user_id: mle-user
